dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml
- codecov
- make clean docs dist
deploy:
  provider: pypi
  user: ohmrefresh
  password:
    secure: IfYpQNthr+P+GvCXxb77CQ3CVd+1puT/7g1mB+48DXt3oCnRQBNzGikkEktBxvLpQkoApuotsMOmoTJaqhF6sNRO4HAHnpx5xQ2bRqS2iV1areO1jHJjRqcAf/33bI4DQiM2zLEoqLqN6DW50QmkkVF/OJ2bIH9E13Ku+IePK0PFVo9ywPozyFZJqVCaXZqDm01WP3D0gzq3fB2ugUfaeHrz3ZBbv3KfyQXpTyOdKV3npCPt0RQydpOJSD7OCBHRkFN1vuJXUOf2DVcQ5/bljH5gXKG/ut/03Tyn7KCX1gvrYo0VKRWKPuBVJf9TaPkeAerebrJRNXOZXXk1WsjdgglanE+m4L+idjjZYOSSJwaS05FN8mVSRmzUELjxYkj5kY4nq8DbK/v/+unSu469F3X/dKeAAflIZz9sPtRQh+l2MAs9pEY0KK6kYAmuJhsdgzUeokLunx74g7JZyTMlmzEH4mHFP5jrC1XaZRwX98BUBopyjDv+ID8v7w2nNGSQeOUHFdteSc/egUGpcwbDO/Epif3CL/nb+Jiga+770UmrhHSR7Es+iGZxR/2OeykDh0haSu7ivU8oyMdk6gyYaqDmp5jl1XCuUDm9SjJb8tqFXawT6glo58XFPCEUZM5oy+63AaYQNqH8nbEY4FbrNB4ysV9N3i0bCUpEMjfuq2g=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ohmrefresh/grafana-snapshot