dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml
- codecov
- make clean docs dist
deploy:
  provider: pypi
  user: ohmrefresh
  password:
    secure: YiB17hLi0ZgGXnV07/8PKhgo5UgyKKLIXYSSMwhoDJnc4GaFB3bynxfDpFevMQgzkmecLYh/opAQtLn8GNYErmQruEWhU50Zw12rQQIi6SLdC+9iLYtZKNlVdiOkxV6M3Xc0k6so3oUa7BmEHsSXa4crZfwzY7iOI08Ak3hj4H33skbuW7ojw72GllvRq2AFIf7ld4fXYvyBmMaWNBISRazD9EEFC6L6eh55+Zw4Z9XUHm4Ud6nQ4eVvSTiZG12runf7pUpm8lUIIrksdFyqpF2wwIXOOC+mAzhW8cqPgPJ7eNCiasr09oMmTWVi8Aj6i3AAIM+tcE9m75tMi/lTOJ7Dl7cbEjTJPR/Nfl5dUnsASHLk/izjTJkIOT8g1ev7N3dO3zEkgGL6LfeRNUaekKg1T9q0nBJsxjxPqp8ZfPo/2hJsI57BZsze2W1wYSowjr6X+RvsDx+GgSm6J/mJjlXxamHNTK5B8HF9yHRLvpst/gRSKE0NGOtzAkucMdng7dAypi2vf3aycNVix/xNTEmUUF53uAn3AkYayqYE4fqPGRgl+oqZaNSbDkQN5qILaFkcrIJUH/CIenErP2Ojx1/TegsL0XLQihlpRiCFYYjcryjLYs7DXdR5En3Xq/8yCUs/KTID18l6k+Tql28UcxhiT8X4MTM0MwQ2QPNbbEM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ascendcorp/grafana-snapshot
